# Generated by Django 5.0.2 on 2025-10-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platillo',
            options={'managed': True},
        ),
    ]
