# Generated by Django 5.0.2 on 2025-10-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_alter_platillo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='platillo',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
