# Generated by Django 5.0.2 on 2025-11-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_platillo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Mesero', 'Mesero'), ('Cocinero', 'Cocinero')], max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='platillo',
            options={'managed': False},
        ),
    ]
